export const CHANGE_FOOTER_HEIGHT = 'CHANGE_FOOTER_HEIGHT';
export const CHANGE_FOOTER_TO_TOP = 'CHANGE_FOOTER_TO_TOP';
export const CHANGE_S_MENU = 'CHANGE_S_MENU';
export const CHANGE_S_RECOMMAND = 'CHANGE_S_RECOMMAND';
export const CHANGE_ID = 'CHANGE_ID';
export const CHANGE_ARTICLE_LIST = 'CHANGE_ARTICLE_LIST';
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const CHANGE_EDIT_ARTICLE = 'CHANGE_EDIT_ARTICLE';