export const CHANGE_FOOTER_HEIGHT = 'CHANGE_FOOTER_HEIGHT';
export const CHANGE_FOOTER_TO_TOP = 'CHANGE_FOOTER_TO_TOP';
export const CHANGE_S_MENU = 'CHANGE_S_MENU';
export const CHANGE_S_RECOMMAND = 'CHANGE_S_RECOMMAND';